version: 2

models:
  - name: dim_region
    description: "Dimension table for electricity regions"
    columns:
      - name: REGION_KEY
        description: "Surrogate key for region"
        tests:
          - unique
          - not_null
      - name: RESPONDENT
        description: "Region code"
        tests:
          - unique
          - not_null

  - name: dim_date
    description: "Dimension table for dates"
    columns:
      - name: DATE_KEY
        description: "Date key in YYYYMMDD format"
        tests:
          - unique
          - not_null
      - name: DATE_VALUE
        description: "Actual date value"
        tests:
          - unique
          - not_null

  - name: fct_hourly_demand
    description: "Fact table for hourly electricity demand"
    columns:
      - name: DEMAND_KEY
        description: "Surrogate key for demand record"
        tests:
          - unique
          - not_null
      - name: PERIOD_DATE
        description: "Timestamp of demand reading"
        tests:
          - not_null
      - name: DEMAND_VALUE
        description: "Demand value in MWh"
        tests:
          - not_null
      - name: REGION_KEY
        description: "Foreign key to dim_region"
        tests:
          - not_null
          - relationships:
              to: ref('dim_region')
              field: REGION_KEY
      - name: DATE_KEY
        description: "Foreign key to dim_date"
        tests:
          - relationships:
              to: ref('dim_date')
              field: DATE_KEY

  - name: analytics_demand_summary
    description: "Aggregated demand metrics for analytics and visualization"
    columns:
      - name: SUMMARY_KEY
        description: "Surrogate key for summary record"
        tests:
          - unique
          - not_null
      - name: TOTAL_DEMAND
        description: "Total demand for the period"
        tests:
          - not_null
