name: 'electricity_forecast'
version: '1.0.0'
config-version: 2
profile: 'electricity_forecast'

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  electricity_forecast:
    staging:
      +materialized: view
    marts:
      +materialized: table
